import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/modules/layout/navbar/templates/navbar";
import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <>
      <Navbar/>
      {children}
      </>
  );
}
